import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiOutlineWhatsApp,
  AiFillYoutube,
  PiWhatsappLogoFill,
} from "react-icons/ai";
import { CgMail } from "react-icons/cg";
import { SiGooglemaps } from "react-icons/si";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
// import deved from "../public/dev-ed-wave.png";
import kucing from "../public/kucingv.png";
import code from "../public/timbang.png";
import design from "../public/konsultasi.png";
import consulting from "../public/kontrak.png";
import Image from "next/image";
import web1 from "../public/ofice1.jpeg";
import web2 from "../public/ofice2.jpeg";
import web3 from "../public/ofice3.jpeg";
import web4 from "../public/ofice4.jpeg";
// import web5 from "../public/web5.png";
// import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Notaris | Idam Hudi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Notrais Idam Hudi</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              {/* <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li> */}
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Idam Hudi, S.H.,M.Kn.
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Notaris.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Tuntaskan Pemenuhan Hak Legal Anda, Raih Keamanan Hukum Bersama Kami: Notaris, Pelindung Kepastian dan Pembuat Kenangan.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="#"> <CgMail /></a>
              <a href="https://wa.me/6281310649885" target="_blank"><AiOutlineWhatsApp /></a>
              <a href="https://maps.app.goo.gl/TvH46wtcvwNmmkDFA" target="_blank"><SiGooglemaps /></a>
            </div>
            {/*  */}
            {/* <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={kucing} layout="fill" objectFit="cover" />
            </div> */}
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Pelayanan</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Pelayanan utama kami mencakup pembuatan <span className="text-teal-500">Akta</span> Notaris yang berkaitan dengan berbagai transaksi dan perjanjian. Apakah Anda sedang menjalani proses jual beli properti, mendirikan perusahaan, atau membagi harta warisan, kami di sini untuk membantu Anda menyusun dokumen-dokumen <span className="text-teal-500">hukum</span> yang sah dan sesuai dengan ketentuan perundang-undangan.
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Verifikasi Dokumen
              </h3>
              <p className="py-2 text-teal-600">
                Pendaftaran Dan Pengesahan Legalisir.
              </p>
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Verifikasi keabsahan dokumen-dokumen hukum</p>
              <p className="text-gray-800 py-1">Pendaftaran dokumen-dokumen tertentu di kantor pertanahan atau lembaga terkait</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Surat Kuasa
              </h3>
              <p className="py-2 text-teal-600">
                Pembuatan Surat Kuasa.
              </p>
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Pembuatan akta kuasa.</p>
              <p className="text-gray-800 py-1">Pembuatan surat kuasa khusus</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Akta Notaris</h3>
              <p className="py-2 text-teal-600">Pembuatan akta pendirian perusahaan
              </p>
              {/* <h4 className="py-4 text-teal-600">Pembuatan akta perubahan anggaran dasar perusahaan</h4> */}
              <p className="text-gray-800 py-1">Akta CV</p>
              <p className="text-gray-800 py-1">Akta PT</p>
              <p className="text-gray-800 py-1">Perjanjian</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Galeri</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Kantor hukum saya, tempat di mana kepastian hukum bertemu dengan pelayanan berkualitas tinggi.kami menciptakan lingkungan yang mendukung kolaborasi kreatif dan diskusi hukum yang mendalam.

              Lokasi kantor kami strategis, memberikan akses mudah bagi klien dan mitra bisnis kami,Lokasi Kantor kami di <span className="text-teal-500">Cirebon </span>
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
